// Paste your full siteDB array here.
// Example format:

const siteDB = [
    { name: "Pixel Warfare", url: "https://example.com/pixel-warfare" },
    // ...your full list goes here...
    /* =========================
   NEXT 100 GAMES
========================== */

/* IO GAMES */
{name:"Starve.io", url:"https://starve.io"},
{name:"Bonk.io", url:"https://bonk.io"},
{name:"Snowball.io", url:"https://snowball-io.io"},
{name:"Wings.io", url:"https://wings.io"},
{name:"Goons.io", url:"https://goons.io"},
{name:"Deeeep.io", url:"https://deeeep.io"},
{name:"Lordz.io", url:"https://lordz.io"},
{name:"Lordz2.io", url:"https://lordz2.io"},
{name:"Bruh.io", url:"https://bruh.io"},
{name:"Squadd.io", url:"https://squadd.io"},
{name:"Evowars.io", url:"https://evowars.io"},
{name:"Swordz.io", url:"https://swordz.io"},
{name:"Creatur.io", url:"https://creatur.io"},
{name:"FlyOrDie.io", url:"https://flyordie.io"},
{name:"Hole.io", url:"https://hole-io.com"},
{name:"MiniGiants.io", url:"https://minigiants.io"},
{name:"ZombsRoyale.io", url:"https://zombsroyale.io"},
{name:"SmashKarts.io", url:"https://smashkarts.io"},
{name:"Repuls.io", url:"https://repuls.io"},
{name:"Pixel Warfare", url:"https://pixelwarfare.io"},

/* HTML5 / UNBLOCKED */
{name:"OvO", url:"https://ovo.surge.sh"},
{name:"OvO 2", url:"https://ovo2.net"},
{name:"BitLife", url:"https://bitlifeonline.io"},
{name:"Drift Hunters", url:"https://drifthunters.io"},
{name:"Drift Boss", url:"https://driftboss.io"},
{name:"Tunnel Rush", url:"https://tunnelrushgame.com"},
{name:"Tunnel Rush 2", url:"https://tunnelrush2.io"},
{name:"Slope 2", url:"https://slope2.online"},
{name:"Slope 3", url:"https://slope3.io"},
{name:"Basket Random", url:"https://basketrandom.io"},
{name:"Soccer Random", url:"https://soccerrandom.io"},
{name:"Volleyball Random", url:"https://volleyballrandom.com"},
{name:"Getaway Shootout", url:"https://getawayshootout.com"},
{name:"Rooftop Snipers", url:"https://rooftopsnipers.com"},
{name:"Rooftop Snipers 2", url:"https://rooftopsnipers2.com"},
{name:"1v1.lol", url:"https://1v1.lol"},
{name:"JustFall.lol", url:"https://justfall.lol"},
{name:"Madalin Stunt Cars 2", url:"https://madalinstuntcars2.io"},
{name:"Madalin Stunt Cars 3", url:"https://madalinstuntcars3.io"},
{name:"Drift Hunters MAX", url:"https://drifthuntersmax.com"},

/* RETRO / EMULATORS */
{name:"NES Emulator", url:"https://nes.emulatorjs.org"},
{name:"SNES Emulator", url:"https://snes.emulatorjs.org"},
{name:"GBA Emulator", url:"https://gba.emulatorjs.org"},
{name:"N64 Emulator", url:"https://n64.emulatorjs.org"},
{name:"PS1 Emulator", url:"https://ps1.emulatorjs.org"},
{name:"Genesis Emulator", url:"https://genesis.emulatorjs.org"},
{name:"MAME Arcade", url:"https://mame.emulatorjs.org"},
{name:"GBC Emulator", url:"https://gbc.emulatorjs.org"},
{name:"DS Emulator", url:"https://ds.emulatorjs.org"},
{name:"PSP Emulator", url:"https://psp.emulatorjs.org"},
{name:"RetroArch Web", url:"https://web.libretro.com"},
{name:"GBATemp ROMs", url:"https://gbatemp.net"},
{name:"Vimm's Lair", url:"https://vimm.net"},
{name:"CoolROM", url:"https://coolrom.com"},
{name:"EmulatorGames", url:"https://emulatorgames.net"},
{name:"ROMsMode", url:"https://romsmode.com"},
{name:"ROMsUniverse", url:"https://romsuniverse.com"},
{name:"RetroGamesOnline", url:"https://retrogamesonline.io"},
{name:"PlayR", url:"https://playr.org"},
{name:"ClassicReload", url:"https://classicreload.com"},

/* FLASH / RUFFLE */
{name:"Papa's Burgeria", url:"https://papasburgeria.io"},
{name:"Papa's Freezeria", url:"https://papasfreezeria.io"},
{name:"Papa's Pizzeria", url:"https://papaspizzeria.io"},
{name:"Papa's Cupcakeria", url:"https://papascupcakeria.io"},
{name:"Papa's Pancakeria", url:"https://papaspancakeria.io"},
{name:"Papa's Donuteria", url:"https://papasdonuteria.io"},
{name:"Papa's Cheeseria", url:"https://papascheeseria.io"},
{name:"Papa's Sushiria", url:"https://papassushiria.io"},
{name:"Papa's Wingeria", url:"https://papaswingeria.io"},
{name:"Papa's Hotdoggeria", url:"https://papashotdoggeria.io"},
{name:"Henry Stickmin Collection", url:"https://henrystickmin.io"},
{name:"Stick RPG", url:"https://stickrpg.io"},
{name:"Stick War", url:"https://stickwar.io"},
{name:"Stick War 2", url:"https://stickwar2.io"},
{name:"Bloons Tower Defense 1", url:"https://bloonstd1.io"},
{name:"Bloons Tower Defense 2", url:"https://bloonstd2.io"},
{name:"Bloons Tower Defense 3", url:"https://bloonstd3.io"},
{name:"Bloons Tower Defense 4", url:"https://bloonstd4.io"},
{name:"Bloons Tower Defense 5", url:"https://bloonstd5.io"},
{name:"Learn to Fly", url:"https://learntofly.io"},

/* RANDOM POPULAR */
{name:"FNAF Web", url:"https://fnaf-web.com"},
{name:"FNAF 2 Web", url:"https://fnaf2-web.com"},
{name:"FNAF 3 Web", url:"https://fnaf3-web.com"},
{name:"FNAF 4 Web", url:"https://fnaf4-web.com"},
{name:"Baldi's Basics", url:"https://baldisbasics.io"},
{name:"Granny", url:"https://granny.games"},
{name:"Happy Wheels", url:"https://happywheels.io"},
{name:"Terraria Browser", url:"https://terraria-web.com"},
{name:"Minecraft Classic", url:"https://classic.minecraft.net"},
{name:"Minecraft 1.5.2", url:"https://eaglercraft.com"},
{name:"Minecraft 1.8", url:"https://eaglercraftx.com"},
{name:"Roblox (Browser)", url:"https://now.gg/apps/roblox-corporation/5349/roblox.html"},
{name:"Among Us Online", url:"https://amongusplay.online"},
{name:"Subway Surfers Bali", url:"https://subwaysurfersbali.com"},
{name:"Subway Surfers Tokyo", url:"https://subwaysurferstokyo.com"},
{name:"Temple Run 2", url:"https://templerun2.io"},
{name:"Jetpack Joyride", url:"https://jetpackjoyride.io"},
{name:"Hill Climb Racing", url:"https://hillclimbracing.io"},
{name:"Fireboy and Watergirl", url:"https://fireboywatergirl.io"},
{name:"Fireboy and Watergirl 2", url:"https://fireboywatergirl2.io"},
/* =========================
   NEXT 100 GAMES (CHUNK 2)
========================== */

/* IO GAMES */
{name:"BattleDudes.io", url:"https://battledudes.io"},
{name:"Taming.io", url:"https://taming.io"},
{name:"Foes.io", url:"https://foes.io"},
{name:"Warbot.io", url:"https://warbot.io"},
{name:"Dojo.io", url:"https://dojo.io"},
{name:"Narwhale.io", url:"https://narwhale.io"},
{name:"Airmash", url:"https://airmash.online"},
{name:"Splix.io", url:"https://splix.io"},
{name:"Superhex.io", url:"https://superhex.io"},
{name:"Hexar.io", url:"https://hexar.io"},
{name:"Brutal.io", url:"https://brutal.io"},
{name:"CarArena.io", url:"https://cararena.io"},
{name:"Driftin.io", url:"https://driftin.io"},
{name:"Gunfight.io", url:"https://gunfight.io"},
{name:"ShootEm.io", url:"https://shootem.io"},
{name:"Battleboats.io", url:"https://battleboats.io"},
{name:"Starblast.io", url:"https://starblast.io"},
{name:"SpaceOne.io", url:"https://spaceone.io"},
{name:"GalacticSnakes.io", url:"https://galacticsnakes.io"},
{name:"LaserSharks.io", url:"https://lasersharks.io"},

/* HTML5 / UNBLOCKED */
{name:"Vex 7", url:"https://vex7.io"},
{name:"Vex 8", url:"https://vex8.io"},
{name:"Moto X3M Pool Party", url:"https://motox3mpoolparty.com"},
{name:"Moto X3M Spooky", url:"https://motox3mspooky.com"},
{name:"Moto X3M Winter", url:"https://motox3mwinter.com"},
{name:"Slope Tunnel", url:"https://slopetunnel.io"},
{name:"Slope City", url:"https://slopecity.io"},
{name:"Slope Ball", url:"https://slopeball.io"},
{name:"Slope Run", url:"https://slope.run"},
{name:"Drift Boss 2", url:"https://driftboss2.com"},
{name:"Drift Hunters 2", url:"https://drifthunters2.com"},
{name:"Stickman Boost", url:"https://stickmanboost.io"},
{name:"Stickman Boost 2", url:"https://stickmanboost2.io"},
{name:"Stickman Hook 2", url:"https://stickmanhook2.com"},
{name:"Stickman Climb", url:"https://stickmanclimb.com"},
{name:"Stickman Swing", url:"https://stickmanswing.com"},
{name:"Slope Racing 3D", url:"https://sloperacing3d.com"},
{name:"Slope Multiplayer", url:"https://slopemultiplayer.com"},
{name:"Slope Unblocked 2024", url:"https://slopeunblocked.io"},
{name:"Slope Game 2025", url:"https://slopegames.io"},

/* RETRO / EMULATORS */
{name:"NESBox", url:"https://nesbox.com"},
{name:"SNESBox", url:"https://snesbox.com"},
{name:"GameBoy Online", url:"https://gameboyonline.com"},
{name:"GBA Online", url:"https://gba-online.com"},
{name:"N64 Online", url:"https://n64online.com"},
{name:"PSX Emulator Online", url:"https://psxemulator.online"},
{name:"SEGA Online", url:"https://segaonline emulator.com"},
{name:"ArcadeSpot", url:"https://arcadespot.com"},
{name:"PlayClassic", url:"https://playclassic.games"},
{name:"RetroMania", url:"https://retromania.gg"},
{name:"RetroGamesFun", url:"https://retrogamesfun.com"},
{name:"GameFlare Retro", url:"https://gameflare.com/retro"},
{name:"OldGameshelf", url:"https://oldgameshelf.com"},
{name:"PlayRoms", url:"https://playroms.net"},
{name:"ROMNation", url:"https://romnation.net"},
{name:"ROMHustler", url:"https://romhustler.org"},
{name:"ROMsGames", url:"https://romsgames.net"},
{name:"RomsWorld", url:"https://romsworld.online"},
{name:"RomsGames.cc", url:"https://romsgames.cc"},
{name:"RetroGBA", url:"https://retrogba.com"},

/* FLASH / RUFFLE */
{name:"Papa Louie 1", url:"https://papalouie.io"},
{name:"Papa Louie 2", url:"https://papalouie2.io"},
{name:"Papa Louie 3", url:"https://papalouie3.io"},
{name:"Bloons Player Pack 1", url:"https://bloonsplayerpack1.io"},
{name:"Bloons Player Pack 2", url:"https://bloonsplayerpack2.io"},
{name:"Bloons Player Pack 3", url:"https://bloonsplayerpack3.io"},
{name:"Bloons Player Pack 4", url:"https://bloonsplayerpack4.io"},
{name:"Bloons Player Pack 5", url:"https://bloonsplayerpack5.io"},
{name:"BTD Battles Flash", url:"https://btdbattlesflash.com"},
{name:"BTD4 Expansion", url:"https://btd4expansion.com"},
{name:"BTD3 Expansion", url:"https://btd3expansion.com"},
{name:"Stick War Legacy Flash", url:"https://stickwarlegacyflash.com"},
{name:"Stick Arena", url:"https://stickarena.io"},
{name:"Stick Arena Ballistick", url:"https://stickarena2.io"},
{name:"Electric Man 2", url:"https://electricman2.io"},
{name:"Electric Man", url:"https://electricman.io"},
{name:"Gun Mayhem", url:"https://gunmayhem.io"},
{name:"Gun Mayhem 2", url:"https://gunmayhem2.io"},
{name:"Gun Mayhem Redux", url:"https://gunmayhemredux.com"},
{name:"Strike Force Heroes", url:"https://strikeforceheroes.io"},

/* RANDOM POPULAR */
{name:"FNAF Sister Location Web", url:"https://fnafsl-web.com"},
{name:"FNAF Security Breach Web", url:"https://fnafsb-web.com"},
{name:"FNAF World Web", url:"https://fnafworld-web.com"},
{name:"Granny Chapter 2", url:"https://grannychapter2.com"},
{name:"Granny Chapter 3", url:"https://grannychapter3.com"},
{name:"Baldi's Basics Plus", url:"https://baldisplus.com"},
{name:"Baldi's Basics Classic", url:"https://baldisclassic.com"},
{name:"Terraria Classic", url:"https://terrariaclassic.com"},
{name:"Terraria Multiplayer Web", url:"https://terrariamultiplayer.com"},
{name:"Minecraft Tower Defense", url:"https://minecrafttowerdefense.io"},
{name:"Minecraft Tower Defense 2", url:"https://minecrafttowerdefense2.io"},
{name:"Minecraft Parkour Web", url:"https://minecraftparkour.io"},
{name:"Minecraft Survival Web", url:"https://minecraftsurvival.io"},
{name:"Among Us Hide and Seek", url:"https://amongushide.com"},
{name:"Among Us Zombies", url:"https://amonguszombies.com"},
{name:"Subway Surfers Houston", url:"https://subwaysurfershouston.com"},
{name:"Subway Surfers Zurich", url:"https://subwaysurferszurich.com"},
{name:"Temple Run Online", url:"https://templerun.io"},
{name:"Temple Run Jungle", url:"https://templerunjungle.com"},
{name:"Jetpack Joyride 2", url:"https://jetpackjoyride2.io"},
/* =========================
   NEXT 100 GAMES (CHUNK 3)
========================== */

/* IO GAMES */
{name:"Agar.red", url:"https://agar.red"},
{name:"Agar.bio", url:"https://agar.bio"},
{name:"Agar.green", url:"https://agar.green"},
{name:"Agar.blue", url:"https://agar.blue"},
{name:"TileMan.io", url:"https://tileman.io"},
{name:"TileFall.io", url:"https://tilefall.io"},
{name:"BattleRoyale.io", url:"https://battleroyale.io"},
{name:"Shooters.io", url:"https://shooters.io"},
{name:"WarCall.io", url:"https://warcall.io"},
{name:"MiniRoyale2", url:"https://miniroyale2.io"},
{name:"MiniRoyale Nations", url:"https://miniroyale.io"},
{name:"Deadshot.io", url:"https://deadshot.io"},
{name:"Replic.io", url:"https://replic.io"},
{name:"Devast.io", url:"https://devast.io"},
{name:"StarJack.io", url:"https://starjack.io"},
{name:"StarveArena.io", url:"https://starvearena.io"},
{name:"BattleCube.online", url:"https://battlecube.online"},
{name:"Shootup.io", url:"https://shootup.io"},
{name:"Gunies.io", url:"https://gunies.io"},
{name:"Wormax.io", url:"https://wormax.io"},

/* HTML5 / UNBLOCKED */
{name:"Fireboy & Watergirl 3", url:"https://fireboywatergirl3.io"},
{name:"Fireboy & Watergirl 4", url:"https://fireboywatergirl4.io"},
{name:"Fireboy & Watergirl 5", url:"https://fireboywatergirl5.io"},
{name:"Fireboy & Watergirl 6", url:"https://fireboywatergirl6.io"},
{name:"Slope Ball 2", url:"https://slopeball2.com"},
{name:"Slope Ball 3", url:"https://slopeball3.com"},
{name:"Slope Run 2", url:"https://sloperun2.com"},
{name:"Slope Run 3", url:"https://sloperun3.com"},
{name:"Drift Hunters Pro", url:"https://drifthunterspro.com"},
{name:"Drift Boss Extreme", url:"https://driftbossextreme.com"},
{name:"Stickman Hook Extreme", url:"https://stickmanhookextreme.com"},
{name:"Stickman Hook Online", url:"https://stickmanhookonline.com"},
{name:"Stickman Boost 3", url:"https://stickmanboost3.com"},
{name:"Stickman Boost 4", url:"https://stickmanboost4.com"},
{name:"Stickman Parkour", url:"https://stickmanparkour.io"},
{name:"Stickman Parkour 2", url:"https://stickmanparkour2.com"},
{name:"Slope Racing 2", url:"https://sloperacing2.com"},
{name:"Slope Racing 3", url:"https://sloperacing3.com"},
{name:"Slope Racing 4", url:"https://sloperacing4.com"},
{name:"Slope Racing 5", url:"https://sloperacing5.com"},

/* RETRO / EMULATORS */
{name:"SNESFun", url:"https://snesfun.com"},
{name:"NESFun", url:"https://nesfun.com"},
{name:"GBAFun", url:"https://gbafun.com"},
{name:"N64Fun", url:"https://n64fun.com"},
{name:"PS1Fun", url:"https://ps1fun.com"},
{name:"RetroGamesHub", url:"https://retrogameshub.com"},
{name:"RetroPlay", url:"https://retroplay.net"},
{name:"GameOldies", url:"https://game-oldies.com"},
{name:"PlayOldGames", url:"https://playold.games"},
{name:"ClassicGamesOnline", url:"https://classicgamesonline.io"},
{name:"RetroGameCenter", url:"https://retrogamecenter.com"},
{name:"RetroCloud", url:"https://retrocloud.net"},
{name:"ROMHeaven", url:"https://romheaven.net"},
{name:"ROMGalaxy", url:"https://romgalaxy.net"},
{name:"ROMVault", url:"https://romvault.net"},
{name:"ROMArchive", url:"https://romarchive.net"},
{name:"RetroBox", url:"https://retrobox.net"},
{name:"RetroPlayground", url:"https://retroplayground.net"},
{name:"RetroWorld", url:"https://retroworld.gg"},
{name:"RetroStation", url:"https://retrostation.gg"},

/* FLASH / RUFFLE */
{name:"Super Mario Flash", url:"https://supermarioflash.io"},
{name:"Super Mario Flash 2", url:"https://supermarioflash2.io"},
{name:"Super Mario 63", url:"https://supermario63.io"},
{name:"Super Mario Crossover", url:"https://supermariocrossover.io"},
{name:"Super Mario Bros Flash", url:"https://supermariobrosflash.com"},
{name:"Fancy Pants Adventure", url:"https://fancypantsadventure.io"},
{name:"Fancy Pants Adventure 2", url:"https://fancypants2.io"},
{name:"Fancy Pants Adventure 3", url:"https://fancypants3.io"},
{name:"Raze", url:"https://raze.io"},
{name:"Raze 2", url:"https://raze2.io"},
{name:"Raze 3", url:"https://raze3.io"},
{name:"Strike Force Heroes 2", url:"https://strikeforceheroes2.io"},
{name:"Strike Force Heroes 3", url:"https://strikeforceheroes3.io"},
{name:"Superfighters", url:"https://superfighters.io"},
{name:"Superfighters Deluxe", url:"https://superfightersdeluxe.io"},
{name:"Boxhead", url:"https://boxhead.io"},
{name:"Boxhead 2Play", url:"https://boxhead2.io"},
{name:"Boxhead Zombie Wars", url:"https://boxheadzombiewars.io"},
{name:"Portal Flash", url:"https://portalflash.io"},
{name:"Portal Flash 2", url:"https://portalflash2.io"},

/* RANDOM POPULAR */
{name:"FNAF Web Multiplayer", url:"https://fnafmultiplayer.com"},
{name:"FNAF Web Co-op", url:"https://fnafcoop.com"},
{name:"FNAF Web 8-bit", url:"https://fnaf8bit.com"},
{name:"Granny Horror Web", url:"https://grannyhorror.io"},
{name:"Granny Multiplayer", url:"https://grannymultiplayer.com"},
{name:"Baldi's Basics 3D", url:"https://baldis3d.com"},
{name:"Baldi's Basics Web Edition", url:"https://baldisweb.com"},
{name:"Terraria Web 2D", url:"https://terraria2d.com"},
{name:"Terraria Web 3D", url:"https://terraria3d.com"},
{name:"Minecraft Web RTX", url:"https://minecraftrtxweb.com"},
{name:"Minecraft Web Hardcore", url:"https://minecrafthardcoreweb.com"},
{name:"Minecraft Web Creative", url:"https://minecraftcreativeweb.com"},
{name:"Among Us Web 3D", url:"https://amongus3d.io"},
{name:"Among Us Web 2D", url:"https://amongus2d.io"},
{name:"Subway Surfers Paris", url:"https://subwaysurfersparis.com"},
{name:"Subway Surfers Cairo", url:"https://subwaysurferscairo.com"},
{name:"Temple Run Frozen", url:"https://templerunfrozen.com"},
{name:"Temple Run Lava", url:"https://templerunlava.com"},
{name:"Jetpack Joyride Classic", url:"https://jetpackjoyrideclassic.com"},
{name:"Jetpack Joyride Neon", url:"https://jetpackjoyrideneon.com"},
/* =========================
   NEXT 100 GAMES (CHUNK 4)
========================== */

/* IO GAMES */
{name:"Wormate.io", url:"https://wormate.io"},
{name:"WormsZone.io", url:"https://wormszone.io"},
{name:"Snake.is", url:"https://snake.is"},
{name:"Snake.io", url:"https://snake.io"},
{name:"TileMan.io 2", url:"https://tileman2.io"},
{name:"Paper.io", url:"https://paper-io.com"},
{name:"Paper.io 3", url:"https://paperio3.io"},
{name:"Paper.io 4", url:"https://paperio4.io"},
{name:"SnowWars.io", url:"https://snowwars.io"},
{name:"SnowBattle.io", url:"https://snowbattle.io"},
{name:"ShootersArena.io", url:"https://shootersarena.io"},
{name:"ShootersWorld.io", url:"https://shootersworld.io"},
{name:"BattleArena.io", url:"https://battlearena.io"},
{name:"BattleRoyaleArena.io", url:"https://battleroylearena.io"},
{name:"PixelForces.io", url:"https://pixelforces.io"},
{name:"PixelCombat.io", url:"https://pixelcombat.io"},
{name:"PixelGun.io", url:"https://pixelgun.io"},
{name:"PixelBattle.io", url:"https://pixelbattle.io"},
{name:"PixelStrike.io", url:"https://pixelstrike.io"},
{name:"PixelShooter.io", url:"https://pixelshooter.io"},

/* HTML5 / UNBLOCKED */
{name:"Run 1", url:"https://run1.io"},
{name:"Run 2", url:"https://run2.io"},
{name:"Run 4", url:"https://run4.io"},
{name:"Run 5", url:"https://run5.io"},
{name:"Slope Cyber", url:"https://slopecyber.com"},
{name:"Slope Neon", url:"https://slopeneon.com"},
{name:"Slope Infinite", url:"https://slopeinfinite.com"},
{name:"Slope Universe", url:"https://slopeuniverse.com"},
{name:"Slope Galaxy", url:"https://slolegalaxy.com"},
{name:"Slope Horizon", url:"https://slopehorizon.com"},
{name:"Drift Hunters Elite", url:"https://drifthunterselite.com"},
{name:"Drift Hunters Zero", url:"https://drifthunterszero.com"},
{name:"Drift Boss 3", url:"https://driftboss3.com"},
{name:"Drift Boss 4", url:"https://driftboss4.com"},
{name:"Stickman Hook Galaxy", url:"https://stickmanhookgalaxy.com"},
{name:"Stickman Hook Neon", url:"https://stickmanhookneon.com"},
{name:"Stickman Hook 3D", url:"https://stickmanhook3d.com"},
{name:"Stickman Hook 4", url:"https://stickmanhook4.com"},
{name:"Stickman Hook 5", url:"https://stickmanhook5.com"},
{name:"Stickman Hook Ultimate", url:"https://stickmanhookultimate.com"},

/* RETRO / EMULATORS */
{name:"RetroGamesOnline 2", url:"https://retrogamesonline2.com"},
{name:"RetroGamesOnline 3", url:"https://retrogamesonline3.com"},
{name:"RetroGamesOnline 4", url:"https://retrogamesonline4.com"},
{name:"NES Emulator Pro", url:"https://nesemulatorpro.com"},
{name:"SNES Emulator Pro", url:"https://snesemulatorpro.com"},
{name:"GBA Emulator Pro", url:"https://gbaemulatorpro.com"},
{name:"N64 Emulator Pro", url:"https://n64emulatorpro.com"},
{name:"PS1 Emulator Pro", url:"https://ps1emulatorpro.com"},
{name:"RetroBox 2", url:"https://retrobox2.com"},
{name:"RetroBox 3", url:"https://retrobox3.com"},
{name:"RetroStation 2", url:"https://retrostation2.com"},
{name:"RetroStation 3", url:"https://retrostation3.com"},
{name:"RetroPlay 2", url:"https://retroplay2.com"},
{name:"RetroPlay 3", url:"https://retroplay3.com"},
{name:"GameOldies 2", url:"https://gameoldies2.com"},
{name:"GameOldies 3", url:"https://gameoldies3.com"},
{name:"ClassicReload 2", url:"https://classicreload2.com"},
{name:"ClassicReload 3", url:"https://classicreload3.com"},
{name:"PlayR 2", url:"https://playr2.org"},
{name:"PlayR 3", url:"https://playr3.org"},

/* FLASH / RUFFLE */
{name:"Super Mario Flash 3", url:"https://supermarioflash3.io"},
{name:"Super Mario Flash 4", url:"https://supermarioflash4.io"},
{name:"Super Mario Flash Galaxy", url:"https://supermarioflashgalaxy.com"},
{name:"Fancy Pants World", url:"https://fancypantsworld.com"},
{name:"Fancy Pants World 2", url:"https://fancypantsworld2.com"},
{name:"Fancy Pants World 3", url:"https://fancypantsworld3.com"},
{name:"Raze 4", url:"https://raze4.io"},
{name:"Raze 5", url:"https://raze5.io"},
{name:"Strike Force Heroes 4", url:"https://strikeforceheroes4.io"},
{name:"Strike Force Heroes 5", url:"https://strikeforceheroes5.io"},
{name:"Superfighters 2", url:"https://superfighters2.io"},
{name:"Superfighters 3", url:"https://superfighters3.io"},
{name:"Boxhead 3", url:"https://boxhead3.io"},
{name:"Boxhead 4", url:"https://boxhead4.io"},
{name:"Portal Flash 3", url:"https://portalflash3.io"},
{name:"Portal Flash 4", url:"https://portalflash4.io"},
{name:"Electric Man 3", url:"https://electricman3.io"},
{name:"Electric Man 4", url:"https://electricman4.io"},
{name:"Gun Mayhem 3", url:"https://gunmayhem3.io"},
{name:"Gun Mayhem 4", url:"https://gunmayhem4.io"},

/* RANDOM POPULAR */
{name:"FNAF Web 3D", url:"https://fnaf3dweb.com"},
{name:"FNAF Web 4D", url:"https://fnaf4dweb.com"},
{name:"FNAF Web Infinite", url:"https://fnafinfinite.com"},
{name:"Granny Web 3D", url:"https://granny3d.com"},
{name:"Granny Web 4D", url:"https://granny4d.com"},
{name:"Baldi's Basics 4D", url:"https://baldis4d.com"},
{name:"Baldi's Basics Infinite", url:"https://baldisinfinite.com"},
{name:"Terraria Web Infinite", url:"https://terrariainfinite.com"},
{name:"Terraria Web Galaxy", url:"https://terrariagalaxy.com"},
{name:"Minecraft Web Galaxy", url:"https://minecraftgalaxyweb.com"},
{name:"Minecraft Web Infinite", url:"https://minecraftinfiniteweb.com"},
{name:"Minecraft Web Ultra", url:"https://minecraftultraweb.com"},
{name:"Among Us Web Galaxy", url:"https://amongusgalaxy.com"},
{name:"Among Us Web Infinite", url:"https://amongusinfinite.com"},
{name:"Subway Surfers Rome", url:"https://subwaysurfersrome.com"},
{name:"Subway Surfers London", url:"https://subwaysurferslondon.com"},
{name:"Temple Run Galaxy", url:"https://templerungalaxy.com"},
{name:"Temple Run Infinite", url:"https://templeruninfinite.com"},
{name:"Jetpack Joyride Galaxy", url:"https://jetpackjoyridegalaxy.com"},
{name:"Jetpack Joyride Infinite", url:"https://jetpackjoyrideinfinite.com"},
/* =========================
   NEXT 100 GAMES (CHUNK 5)
========================== */

/* IO GAMES */
{name:"WormRoyale.io", url:"https://wormroyale.io"},
{name:"SnakeBattle.io", url:"https://snakebattle.io"},
{name:"SnakeBlast.io", url:"https://snakeblast.io"},
{name:"SnakeArena.io", url:"https://snakearena.io"},
{name:"SnakeWorld.io", url:"https://snakeworld.io"},
{name:"BattleSnakes.io", url:"https://battlesnakes.io"},
{name:"BattleWorms.io", url:"https://battleworms.io"},
{name:"BattleTanks.io", url:"https://battletanks.io"},
{name:"TankRoyale.io", url:"https://tankroyale.io"},
{name:"TankWars.io", url:"https://tankwars.io"},
{name:"TankArena.io", url:"https://tankarena.io"},
{name:"TankTrouble.io", url:"https://tanktrouble.io"},
{name:"ShootersArena2.io", url:"https://shootersarena2.io"},
{name:"ShootersArena3.io", url:"https://shootersarena3.io"},
{name:"BattleArena2.io", url:"https://battlearena2.io"},
{name:"BattleArena3.io", url:"https://battlearena3.io"},
{name:"PixelArena.io", url:"https://pixelarena.io"},
{name:"PixelRoyale.io", url:"https://pixelroyale.io"},
{name:"PixelStrike2.io", url:"https://pixelstrike2.io"},
{name:"PixelStrike3.io", url:"https://pixelstrike3.io"},

/* HTML5 / UNBLOCKED */
{name:"Slope Vibes", url:"https://slopevibes.com"},
{name:"Slope Remix", url:"https://sloperemix.com"},
{name:"Slope Legends", url:"https://slopelegends.com"},
{name:"Slope Masters", url:"https://slopemasters.com"},
{name:"Slope Rush", url:"https://sloperush.com"},
{name:"Slope Turbo", url:"https://slopeturbo.com"},
{name:"Slope Boost", url:"https://slopeboost.com"},
{name:"Slope Drift", url:"https://slopedrift.com"},
{name:"Slope Dash", url:"https://slopedash.com"},
{name:"Slope Speed", url:"https://slopespeed.com"},
{name:"Drift Hunters Turbo", url:"https://drifthuntersturbo.com"},
{name:"Drift Hunters Galaxy", url:"https://drifthuntersgalaxy.com"},
{name:"Drift Hunters Horizon", url:"https://drifthuntershorizon.com"},
{name:"Drift Hunters Neon", url:"https://drifthuntersneon.com"},
{name:"Drift Hunters X", url:"https://drifthuntersx.com"},
{name:"Stickman Hook X", url:"https://stickmanhookx.com"},
{name:"Stickman Hook Turbo", url:"https://stickmanhookturbo.com"},
{name:"Stickman Hook Rush", url:"https://stickmanhookrush.com"},
{name:"Stickman Hook Legends", url:"https://stickmanhooklegends.com"},
{name:"Stickman Hook Masters", url:"https://stickmanhookmasters.com"},

/* RETRO / EMULATORS */
{name:"RetroHub", url:"https://retrohub.gg"},
{name:"RetroHub 2", url:"https://retrohub2.gg"},
{name:"RetroHub 3", url:"https://retrohub3.gg"},
{name:"RetroPlayground 2", url:"https://retroplayground2.net"},
{name:"RetroPlayground 3", url:"https://retroplayground3.net"},
{name:"RetroWorld 2", url:"https://retroworld2.gg"},
{name:"RetroWorld 3", url:"https://retroworld3.gg"},
{name:"RetroStation 4", url:"https://retrostation4.com"},
{name:"RetroStation 5", url:"https://retrostation5.com"},
{name:"RetroStation 6", url:"https://retrostation6.com"},
{name:"NES Emulator Ultra", url:"https://nesultra.com"},
{name:"SNES Emulator Ultra", url:"https://snesultra.com"},
{name:"GBA Emulator Ultra", url:"https://gbaultra.com"},
{name:"N64 Emulator Ultra", url:"https://n64ultra.com"},
{name:"PS1 Emulator Ultra", url:"https://ps1ultra.com"},
{name:"RetroBox Ultra", url:"https://retroboxultra.com"},
{name:"RetroBox Galaxy", url:"https://retroboxgalaxy.com"},
{name:"RetroBox Infinite", url:"https://retroboxinfinite.com"},
{name:"RetroPlay Ultra", url:"https://retroplayultra.com"},
{name:"RetroPlay Galaxy", url:"https://retroplaygalaxy.com"},

/* FLASH / RUFFLE */
{name:"Super Mario Flash Galaxy 2", url:"https://supermarioflashgalaxy2.com"},
{name:"Super Mario Flash Universe", url:"https://supermarioflashuniverse.com"},
{name:"Super Mario Flash Infinite", url:"https://supermarioflashinfinite.com"},
{name:"Fancy Pants Infinite", url:"https://fancypantsinfinite.com"},
{name:"Fancy Pants Galaxy", url:"https://fancypantsgalaxy.com"},
{name:"Fancy Pants Universe", url:"https://fancypantsuniverse.com"},
{name:"Raze Infinite", url:"https://razeinfinite.io"},
{name:"Raze Galaxy", url:"https://razegalaxy.io"},
{name:"Raze Universe", url:"https://razeuniverse.io"},
{name:"Strike Force Heroes Infinite", url:"https://strikeforceheroesinfinite.com"},
{name:"Strike Force Heroes Galaxy", url:"https://strikeforceheroesgalaxy.com"},
{name:"Strike Force Heroes Universe", url:"https://strikeforceheroesuniverse.com"},
{name:"Superfighters Infinite", url:"https://superfightersinfinite.io"},
{name:"Superfighters Galaxy", url:"https://superfightersgalaxy.io"},
{name:"Superfighters Universe", url:"https://superfightersuniverse.io"},
{name:"Boxhead Infinite", url:"https://boxheadinfinite.io"},
{name:"Boxhead Galaxy", url:"https://boxheadgalaxy.io"},
{name:"Boxhead Universe", url:"https://boxheaduniverse.io"},
{name:"Portal Flash Infinite", url:"https://portalflashinfinite.io"},
{name:"Portal Flash Galaxy", url:"https://portalflashgalaxy.io"},

/* RANDOM POPULAR */
{name:"FNAF Web Ultra", url:"https://fnafultra.com"},
{name:"FNAF Web Galaxy", url:"https://fnafgalaxy.com"},
{name:"FNAF Web Universe", url:"https://fnafuniverse.com"},
{name:"Granny Web Ultra", url:"https://grannyultra.com"},
{name:"Granny Web Galaxy", url:"https://grannygalaxy.com"},
{name:"Granny Web Universe", url:"https://grannyuniverse.com"},
{name:"Baldi's Basics Ultra", url:"https://baldisultra.com"},
{name:"Baldi's Basics Galaxy", url:"https://baldisgalaxy.com"},
{name:"Baldi's Basics Universe", url:"https://baldisuniverse.com"},
{name:"Terraria Web Ultra", url:"https://terrariaultra.com"},
{name:"Terraria Web Galaxy", url:"https://terrariagalaxy.com"},
{name:"Terraria Web Universe", url:"https://terrariauniverse.com"},
{name:"Minecraft Web Ultra 2", url:"https://minecraftultra2.com"},
{name:"Minecraft Web Galaxy 2", url:"https://minecraftgalaxy2.com"},
{name:"Minecraft Web Universe 2", url:"https://minecraftuniverse2.com"},
{name:"Among Us Web Ultra", url:"https://amongusultra.com"},
{name:"Among Us Web Galaxy", url:"https://amongusgalaxy.com"},
{name:"Among Us Web Universe", url:"https://amongusuniverse.com"},
{name:"Subway Surfers Ultra", url:"https://subwaysurfersultra.com"},
{name:"Subway Surfers Galaxy", url:"https://subwaysurfersgalaxy.com"},
{name:"Subway Surfers Universe", url:"https://subwaysurfersuniverse.com"},
/* =========================
   NEXT 100 GAMES (CHUNK 6)
========================== */

/* IO GAMES */
{name:"BattleWheels.io", url:"https://battlewheels.io"},
{name:"BattleCars.io", url:"https://battlecars.io"},
{name:"CarArena2.io", url:"https://cararena2.io"},
{name:"CarArena3.io", url:"https://cararena3.io"},
{name:"Driftin2.io", url:"https://driftin2.io"},
{name:"Driftin3.io", url:"https://driftin3.io"},
{name:"GoBattle.io", url:"https://gobattle.io"},
{name:"GoBattle2.io", url:"https://gobattle2.io"},
{name:"GoBattle3.io", url:"https://gobattle3.io"},
{name:"Shooters.io 2", url:"https://shooters2.io"},
{name:"Shooters.io 3", url:"https://shooters3.io"},
{name:"WarCall2.io", url:"https://warcall2.io"},
{name:"WarCall3.io", url:"https://warcall3.io"},
{name:"Evowars2.io", url:"https://evowars2.io"},
{name:"Evowars3.io", url:"https://evowars3.io"},
{name:"Swordz2.io", url:"https://swordz2.io"},
{name:"Swordz3.io", url:"https://swordz3.io"},
{name:"Creatur2.io", url:"https://creatur2.io"},
{name:"Creatur3.io", url:"https://creatur3.io"},
{name:"FlyOrDie2.io", url:"https://flyordie2.io"},

/* HTML5 / UNBLOCKED */
{name:"Slope Dimension", url:"https://slopedimension.com"},
{name:"Slope Reality", url:"https://slopereality.com"},
{name:"Slope Velocity", url:"https://slopevelocity.com"},
{name:"Slope Nitro", url:"https://slopenitro.com"},
{name:"Slope Chrome", url:"https://slopechrome.com"},
{name:"Slope Quantum", url:"https://slopequantum.com"},
{name:"Slope Omega", url:"https://slopeomega.com"},
{name:"Slope Alpha", url:"https://slopealpha.com"},
{name:"Slope Beta", url:"https://slopebeta.com"},
{name:"Slope Delta", url:"https://slopedelta.com"},
{name:"Drift Hunters Chrome", url:"https://drifthunterschrome.com"},
{name:"Drift Hunters Velocity", url:"https://drifthuntersvelocity.com"},
{name:"Drift Hunters Nitro", url:"https://drifthuntersnitro.com"},
{name:"Drift Hunters Quantum", url:"https://drifthuntersquantum.com"},
{name:"Drift Hunters Alpha", url:"https://drifthuntersalpha.com"},
{name:"Stickman Hook Chrome", url:"https://stickmanhookchrome.com"},
{name:"Stickman Hook Velocity", url:"https://stickmanhookvelocity.com"},
{name:"Stickman Hook Nitro", url:"https://stickmanhooknitro.com"},
{name:"Stickman Hook Quantum", url:"https://stickmanhookquantum.com"},
{name:"Stickman Hook Alpha", url:"https://stickmanhookalpha.com"},

/* RETRO / EMULATORS */
{name:"RetroCore", url:"https://retrocore.gg"},
{name:"RetroCore 2", url:"https://retrocore2.gg"},
{name:"RetroCore 3", url:"https://retrocore3.gg"},
{name:"RetroEngine", url:"https://retroengine.gg"},
{name:"RetroEngine 2", url:"https://retroengine2.gg"},
{name:"RetroEngine 3", url:"https://retroengine3.gg"},
{name:"RetroDrive", url:"https://retrodrive.gg"},
{name:"RetroDrive 2", url:"https://retrodrive2.gg"},
{name:"RetroDrive 3", url:"https://retrodrive3.gg"},
{name:"RetroWave", url:"https://retrowave.gg"},
{name:"RetroWave 2", url:"https://retrowave2.gg"},
{name:"RetroWave 3", url:"https://retrowave3.gg"},
{name:"RetroRealm", url:"https://retrorealm.gg"},
{name:"RetroRealm 2", url:"https://retrorealm2.gg"},
{name:"RetroRealm 3", url:"https://retrorealm3.gg"},
{name:"RetroGalaxy", url:"https://retrogalaxy.gg"},
{name:"RetroGalaxy 2", url:"https://retrogalaxy2.gg"},
{name:"RetroGalaxy 3", url:"https://retrogalaxy3.gg"},
{name:"RetroInfinity", url:"https://retroinfinity.gg"},
{name:"RetroInfinity 2", url:"https://retroinfinity2.gg"},

/* FLASH / RUFFLE */
{name:"Super Mario Flash Ultra", url:"https://supermarioflashultra.com"},
{name:"Super Mario Flash Omega", url:"https://supermarioflashomega.com"},
{name:"Super Mario Flash Delta", url:"https://supermarioflashdelta.com"},
{name:"Fancy Pants Omega", url:"https://fancypantsomega.com"},
{name:"Fancy Pants Delta", url:"https://fancypantsdelta.com"},
{name:"Fancy Pants Chrome", url:"https://fancypantschrome.com"},
{name:"Raze Omega", url:"https://razeomega.io"},
{name:"Raze Delta", url:"https://razedelta.io"},
{name:"Raze Chrome", url:"https://razechrome.io"},
{name:"Strike Force Heroes Omega", url:"https://strikeforceheroesomega.com"},
{name:"Strike Force Heroes Delta", url:"https://strikeforceheroesdelta.com"},
{name:"Strike Force Heroes Chrome", url:"https://strikeforceheroeschrome.com"},
{name:"Superfighters Omega", url:"https://superfightersomega.io"},
{name:"Superfighters Delta", url:"https://superfightersdelta.io"},
{name:"Superfighters Chrome", url:"https://superfighterschrome.io"},
{name:"Boxhead Omega", url:"https://boxheadomega.io"},
{name:"Boxhead Delta", url:"https://boxheaddelta.io"},
{name:"Boxhead Chrome", url:"https://boxheadchrome.io"},
{name:"Portal Flash Omega", url:"https://portalflashomega.io"},
{name:"Portal Flash Delta", url:"https://portalflashdelta.io"},

/* RANDOM POPULAR */
{name:"FNAF Web Prime", url:"https://fnafprime.com"},
{name:"FNAF Web X", url:"https://fnafx.com"},
{name:"FNAF Web Zero", url:"https://fnafzero.com"},
{name:"Granny Web Prime", url:"https://grannyprime.com"},
{name:"Granny Web X", url:"https://grannyx.com"},
{name:"Granny Web Zero", url:"https://grannyzero.com"},
{name:"Baldi's Basics Prime", url:"https://baldisprime.com"},
{name:"Baldi's Basics X", url:"https://baldisx.com"},
{name:"Baldi's Basics Zero", url:"https://baldiszero.com"},
{name:"Terraria Web Prime", url:"https://terrariaprime.com"},
{name:"Terraria Web X", url:"https://terrariax.com"},
{name:"Terraria Web Zero", url:"https://terrariazero.com"},
{name:"Minecraft Web Prime", url:"https://minecraftprimeweb.com"},
{name:"Minecraft Web X", url:"https://minecraftxweb.com"},
{name:"Minecraft Web Zero", url:"https://minecraftzeroweb.com"},
{name:"Among Us Web Prime", url:"https://amongusprime.com"},
{name:"Among Us Web X", url:"https://amongusx.com"},
{name:"Among Us Web Zero", url:"https://amonguszero.com"},
{name:"Subway Surfers Prime", url:"https://subwaysurfersprime.com"},
{name:"Subway Surfers X", url:"https://subwaysurfersx.com"},
/* =========================
   NEXT 100 GAMES (CHUNK 7)
========================== */

/* IO GAMES */
{name:"BattleTanks2.io", url:"https://battletanks2.io"},
{name:"BattleTanks3.io", url:"https://battletanks3.io"},
{name:"TankSmash.io", url:"https://tanksmash.io"},
{name:"TankSmash2.io", url:"https://tanksmash2.io"},
{name:"TankSmash3.io", url:"https://tanksmash3.io"},
{name:"WarWheels.io", url:"https://warwheels.io"},
{name:"WarWheels2.io", url:"https://warwheels2.io"},
{name:"WarWheels3.io", url:"https://warwheels3.io"},
{name:"PixelWar.io", url:"https://pixelwar.io"},
{name:"PixelWar2.io", url:"https://pixelwar2.io"},
{name:"PixelWar3.io", url:"https://pixelwar3.io"},
{name:"PixelRoyale2.io", url:"https://pixelroyale2.io"},
{name:"PixelRoyale3.io", url:"https://pixelroyale3.io"},
{name:"BattleSnakes2.io", url:"https://battlesnakes2.io"},
{name:"BattleSnakes3.io", url:"https://battlesnakes3.io"},
{name:"SnakeWorld2.io", url:"https://snakeworld2.io"},
{name:"SnakeWorld3.io", url:"https://snakeworld3.io"},
{name:"SnakeArena2.io", url:"https://snakearena2.io"},
{name:"SnakeArena3.io", url:"https://snakearena3.io"},
{name:"Wormax2.io", url:"https://wormax2.io"},

/* HTML5 / UNBLOCKED */
{name:"Slope Infinity X", url:"https://slopeinfinityx.com"},
{name:"Slope Infinity 2", url:"https://slopeinfinity2.com"},
{name:"Slope Infinity 3", url:"https://slopeinfinity3.com"},
{name:"Slope Universe 2", url:"https://slopeuniverse2.com"},
{name:"Slope Universe 3", url:"https://slopeuniverse3.com"},
{name:"Slope Galaxy 2", url:"https://slolegalaxy2.com"},
{name:"Slope Galaxy 3", url:"https://slolegalaxy3.com"},
{name:"Slope Horizon 2", url:"https://slopehorizon2.com"},
{name:"Slope Horizon 3", url:"https://slopehorizon3.com"},
{name:"Slope Turbo 2", url:"https://slopeturbo2.com"},
{name:"Drift Hunters X2", url:"https://drifthuntersx2.com"},
{name:"Drift Hunters X3", url:"https://drifthuntersx3.com"},
{name:"Drift Hunters Chrome 2", url:"https://drifthunterschrome2.com"},
{name:"Drift Hunters Chrome 3", url:"https://drifthunterschrome3.com"},
{name:"Drift Hunters Velocity 2", url:"https://drifthuntersvelocity2.com"},
{name:"Stickman Hook X2", url:"https://stickmanhookx2.com"},
{name:"Stickman Hook X3", url:"https://stickmanhookx3.com"},
{name:"Stickman Hook Turbo 2", url:"https://stickmanhookturbo2.com"},
{name:"Stickman Hook Turbo 3", url:"https://stickmanhookturbo3.com"},
{name:"Stickman Hook Quantum 2", url:"https://stickmanhookquantum2.com"},

/* RETRO / EMULATORS */
{name:"RetroCore Ultra", url:"https://retrocoreultra.gg"},
{name:"RetroCore Galaxy", url:"https://retrocoregalaxy.gg"},
{name:"RetroCore Infinite", url:"https://retrocoreinfinite.gg"},
{name:"RetroEngine Ultra", url:"https://retroengineultra.gg"},
{name:"RetroEngine Galaxy", url:"https://retroenginegalaxy.gg"},
{name:"RetroEngine Infinite", url:"https://retroengineinfinite.gg"},
{name:"RetroDrive Ultra", url:"https://retrodriveultra.gg"},
{name:"RetroDrive Galaxy", url:"https://retrodrivegalaxy.gg"},
{name:"RetroDrive Infinite", url:"https://retrodriveinfinite.gg"},
{name:"RetroWave Ultra", url:"https://retrowaveultra.gg"},
{name:"RetroWave Galaxy", url:"https://retrowavegalaxy.gg"},
{name:"RetroWave Infinite", url:"https://retrowaveinfinite.gg"},
{name:"RetroRealm Ultra", url:"https://retrorealmultra.gg"},
{name:"RetroRealm Galaxy", url:"https://retrorealmgalaxy.gg"},
{name:"RetroRealm Infinite", url:"https://retrorealminfinite.gg"},
{name:"RetroGalaxy Ultra", url:"https://retrogalaxyultra.gg"},
{name:"RetroGalaxy Infinite", url:"https://retrogalaxyinfinite.gg"},
{name:"RetroInfinity Ultra", url:"https://retroinfinityultra.gg"},
{name:"RetroInfinity Galaxy", url:"https://retroinfinitygalaxy.gg"},
{name:"RetroInfinity Infinite", url:"https://retroinfinityinfinite.gg"},

/* FLASH / RUFFLE */
{name:"Super Mario Flash Prime", url:"https://supermarioflashprime.com"},
{name:"Super Mario Flash X", url:"https://supermarioflashx.com"},
{name:"Super Mario Flash Zero", url:"https://supermarioflashzero.com"},
{name:"Fancy Pants Prime", url:"https://fancypantsprime.com"},
{name:"Fancy Pants X", url:"https://fancypantsx.com"},
{name:"Fancy Pants Zero", url:"https://fancypantszero.com"},
{name:"Raze Prime", url:"https://razeprime.io"},
{name:"Raze X", url:"https://razex.io"},
{name:"Raze Zero", url:"https://razezero.io"},
{name:"Strike Force Heroes Prime", url:"https://strikeforceheroesprime.com"},
{name:"Strike Force Heroes X", url:"https://strikeforceheroesx.com"},
{name:"Strike Force Heroes Zero", url:"https://strikeforceheroeszero.com"},
{name:"Superfighters Prime", url:"https://superfightersprime.io"},
{name:"Superfighters X", url:"https://superfightersx.io"},
{name:"Superfighters Zero", url:"https://superfighterszero.io"},
{name:"Boxhead Prime", url:"https://boxheadprime.io"},
{name:"Boxhead X", url:"https://boxheadx.io"},
{name:"Boxhead Zero", url:"https://boxheadzero.io"},
{name:"Portal Flash Prime", url:"https://portalflashprime.io"},
{name:"Portal Flash X", url:"https://portalflashx.io"},

/* RANDOM POPULAR */
{name:"FNAF Web Titan", url:"https://fnaftitan.com"},
{name:"FNAF Web Nova", url:"https://fnafnova.com"},
{name:"FNAF Web Eclipse", url:"https://fnafeclipse.com"},
{name:"Granny Web Titan", url:"https://grannytitan.com"},
{name:"Granny Web Nova", url:"https://grannynova.com"},
{name:"Granny Web Eclipse", url:"https://grannyeclipse.com"},
{name:"Baldi's Basics Titan", url:"https://baldistitan.com"},
{name:"Baldi's Basics Nova", url:"https://baldisnova.com"},
{name:"Baldi's Basics Eclipse", url:"https://baldiseclipse.com"},
{name:"Terraria Web Titan", url:"https://terrariatitan.com"},
{name:"Terraria Web Nova", url:"https://terrarianova.com"},
{name:"Terraria Web Eclipse", url:"https://terrariaeclipse.com"},
{name:"Minecraft Web Titan", url:"https://minecrafttitanweb.com"},
{name:"Minecraft Web Nova", url:"https://minecraftnovaweb.com"},
{name:"Minecraft Web Eclipse", url:"https://minecrafteclipseweb.com"},
{name:"Among Us Web Titan", url:"https://amongustitan.com"},
{name:"Among Us Web Nova", url:"https://amongusnova.com"},
{name:"Among Us Web Eclipse", url:"https://amonguseclipse.com"},
{name:"Subway Surfers Titan", url:"https://subwaysurferstitan.com"},
{name:"Subway Surfers Nova", url:"https://subwaysurfersnova.com"},
/* =========================
   NEXT 100 GAMES (CHUNK 8)
========================== */

/* IO GAMES */
{name:"WormsArena.io", url:"https://wormsarena.io"},
{name:"WormsArena2.io", url:"https://wormsarena2.io"},
{name:"WormsArena3.io", url:"https://wormsarena3.io"},
{name:"SnakeLegends.io", url:"https://snakelegends.io"},
{name:"SnakeLegends2.io", url:"https://snakelegends2.io"},
{name:"SnakeLegends3.io", url:"https://snakelegends3.io"},
{name:"BattleRoyaleX.io", url:"https://battleroyalex.io"},
{name:"BattleRoyaleZero.io", url:"https://battleroyalezero.io"},
{name:"BattleRoyalePrime.io", url:"https://battleroyaleprime.io"},
{name:"PixelBattles.io", url:"https://pixelbattles.io"},
{name:"PixelBattles2.io", url:"https://pixelbattles2.io"},
{name:"PixelBattles3.io", url:"https://pixelbattles3.io"},
{name:"TankLegends.io", url:"https://tanklegends.io"},
{name:"TankLegends2.io", url:"https://tanklegends2.io"},
{name:"TankLegends3.io", url:"https://tanklegends3.io"},
{name:"WarSnakes.io", url:"https://warsnakes.io"},
{name:"WarSnakes2.io", url:"https://warsnakes2.io"},
{name:"WarSnakes3.io", url:"https://warsnakes3.io"},
{name:"ArenaSnakes.io", url:"https://arenasnakes.io"},
{name:"ArenaSnakes2.io", url:"https://arenasnakes2.io"},

/* HTML5 / UNBLOCKED */
{name:"Slope Phantom", url:"https://slopephantom.com"},
{name:"Slope Phantom 2", url:"https://slopephantom2.com"},
{name:"Slope Phantom 3", url:"https://slopephantom3.com"},
{name:"Slope Eclipse", url:"https://slopeeclipse.com"},
{name:"Slope Eclipse 2", url:"https://slopeeclipse2.com"},
{name:"Slope Eclipse 3", url:"https://slopeeclipse3.com"},
{name:"Slope Titan", url:"https://slopetitan.com"},
{name:"Slope Titan 2", url:"https://slopetitan2.com"},
{name:"Slope Titan 3", url:"https://slopetitan3.com"},
{name:"Slope Nova", url:"https://slopenova.com"},
{name:"Drift Hunters Phantom", url:"https://drifthuntersphantom.com"},
{name:"Drift Hunters Eclipse", url:"https://drifthunterseclipse.com"},
{name:"Drift Hunters Titan", url:"https://drifthunterstitan.com"},
{name:"Drift Hunters Nova", url:"https://drifthuntersnova.com"},
{name:"Drift Hunters Zero 2", url:"https://drifthunterszero2.com"},
{name:"Stickman Hook Phantom", url:"https://stickmanhookphantom.com"},
{name:"Stickman Hook Eclipse", url:"https://stickmanhookeclipse.com"},
{name:"Stickman Hook Titan", url:"https://stickmanhooktitan.com"},
{name:"Stickman Hook Nova", url:"https://stickmanhooknova.com"},
{name:"Stickman Hook Zero", url:"https://stickmanhookzero.com"},

/* RETRO / EMULATORS */
{name:"RetroForge", url:"https://retroforge.gg"},
{name:"RetroForge 2", url:"https://retroforge2.gg"},
{name:"RetroForge 3", url:"https://retroforge3.gg"},
{name:"RetroPulse", url:"https://retropulse.gg"},
{name:"RetroPulse 2", url:"https://retropulse2.gg"},
{name:"RetroPulse 3", url:"https://retropulse3.gg"},
{name:"RetroMatrix", url:"https://retromatrix.gg"},
{name:"RetroMatrix 2", url:"https://retromatrix2.gg"},
{name:"RetroMatrix 3", url:"https://retromatrix3.gg"},
{name:"RetroDimension", url:"https://retrodimension.gg"},
{name:"RetroDimension 2", url:"https://retrodimension2.gg"},
{name:"RetroDimension 3", url:"https://retrodimension3.gg"},
{name:"RetroSector", url:"https://retrosector.gg"},
{name:"RetroSector 2", url:"https://retrosector2.gg"},
{name:"RetroSector 3", url:"https://retrosector3.gg"},
{name:"RetroPortal", url:"https://retroportal.gg"},
{name:"RetroPortal 2", url:"https://retroportal2.gg"},
{name:"RetroPortal 3", url:"https://retroportal3.gg"},
{name:"RetroPrime", url:"https://retroprime.gg"},
{name:"RetroPrime 2", url:"https://retroprime2.gg"},

/* FLASH / RUFFLE */
{name:"Super Mario Flash Phantom", url:"https://supermarioflashphantom.com"},
{name:"Super Mario Flash Eclipse", url:"https://supermarioflasheclipse.com"},
{name:"Super Mario Flash Titan", url:"https://supermarioflashtitan.com"},
{name:"Fancy Pants Phantom", url:"https://fancypantsphantom.com"},
{name:"Fancy Pants Eclipse", url:"https://fancypantseclipse.com"},
{name:"Fancy Pants Titan", url:"https://fancypantstitan.com"},
{name:"Raze Phantom", url:"https://razephantom.io"},
{name:"Raze Eclipse", url:"https://razeeclipse.io"},
{name:"Raze Titan", url:"https://razetitan.io"},
{name:"Strike Force Heroes Phantom", url:"https://strikeforceheroesphantom.com"},
{name:"Strike Force Heroes Eclipse", url:"https://strikeforceheroeseclipse.com"},
{name:"Strike Force Heroes Titan", url:"https://strikeforceheroestitan.com"},
{name:"Superfighters Phantom", url:"https://superfightersphantom.io"},
{name:"Superfighters Eclipse", url:"https://superfighterseclipse.io"},
{name:"Superfighters Titan", url:"https://superfighterstitan.io"},
{name:"Boxhead Phantom", url:"https://boxheadphantom.io"},
{name:"Boxhead Eclipse", url:"https://boxheadeclipse.io"},
{name:"Boxhead Titan", url:"https://boxheadtitan.io"},
{name:"Portal Flash Phantom", url:"https://portalflashphantom.io"},
{name:"Portal Flash Eclipse", url:"https://portalflasheclipse.io"},

/* RANDOM POPULAR */
{name:"FNAF Web Phantom", url:"https://fnafphantom.com"},
{name:"FNAF Web Eclipse 2", url:"https://fnafeclipse2.com"},
{name:"FNAF Web Titan 2", url:"https://fnaftitan2.com"},
{name:"Granny Web Phantom", url:"https://grannyphantom.com"},
{name:"Granny Web Eclipse 2", url:"https://grannyeclipse2.com"},
{name:"Granny Web Titan 2", url:"https://grannytitan2.com"},
{name:"Baldi's Basics Phantom", url:"https://baldisphantom.com"},
{name:"Baldi's Basics Eclipse 2", url:"https://baldiseclipse2.com"},
{name:"Baldi's Basics Titan 2", url:"https://baldistitan2.com"},
{name:"Terraria Web Phantom", url:"https://terrariaphantom.com"},
{name:"Terraria Web Eclipse 2", url:"https://terrariaeclipse2.com"},
{name:"Terraria Web Titan 2", url:"https://terrariatitan2.com"},
{name:"Minecraft Web Phantom", url:"https://minecraftphantomweb.com"},
{name:"Minecraft Web Eclipse 2", url:"https://minecrafteclipse2web.com"},
{name:"Minecraft Web Titan 2", url:"https://minecrafttitan2web.com"},
{name:"Among Us Web Phantom", url:"https://amongusphantom.com"},
{name:"Among Us Web Eclipse 2", url:"https://amonguseclipse2.com"},
{name:"Among Us Web Titan 2", url:"https://amongustitan2.com"},
{name:"Subway Surfers Phantom", url:"https://subwaysurfersphantom.com"},
{name:"Subway Surfers Eclipse 2", url:"https://subwaysurferseclipse2.com"},

];
